### ISSUE TITLE
Error naming is inconsistent and should accept an optional error

### ISSUE THREAD

**Issue by erizocosmico** [src-d/go-log#4]
Right now all methods of the logger are like `LEVELf`, except error, which is `Error`. This would make sense if error wouldn't allow formatting, but it does. It just feels a little inconsistent.

Also, it always requires an `error`. But you may not want to log an `error`, but just a message that happens to be an error. It should accept `nil` and add it to the log only if `err` is not nil so that you can optionally not pass an error.

What do you think?

**Comment by mcuadros** [comment]
Totally rightl
